[package]
name = "anathema-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anathema-widget-core = { path = "../anathema-widget-core" }
anathema-render = { path = "../anathema-render" }
flume = { workspace = true }
crossterm = { workspace = true }
